### ISSUE TITLE
illegal instrucion (core dumped)

### ISSUE THREAD

**Issue by lili-ph** [mailhexu/TB2J#16]
dear developer,

I did a non-collinear calculation with epenmx for a unit cell of 12 atom. I encountered this problem with tb2j-openmx :

Loading from scfout file OK!
starting to calculate exchange.
Green's function calculation started.
Illegal instruction (core dumped)

These are the details of my pc:
memory 64 GiB
processor intel xeon(R) CPU E5-2620 v2 @ 2.10GHz * 24

How can I fix this problem?
Thank you in advance for your help

**Comment by mailhexu** [comment]
Hi, 
Illegal instruction usually happens when the program is compiled on a machine different from the one you're running the code on, and the two machines have different instruction set. Likely the compilation machine is newer. 
Since it is during the step of computing the Green's function, it is likely that it is  numpy or scipy are not the right version. 
Could you try doing it on another computer? Or try a different way to install numpy/scipy  (use conda for example). 
Best wishes,
HeXu

**Comment by lili-ph** [comment]
Dear HeXu,
Thank you very much for this quick reply.
Your advice was absolutely correct. I deleted the program and recompiled it and now it is working.
With best regards,
Lili
